all:          # this is a group that always exists regardless of if it is declared
  vars:       # inventory group_vars/all    ansible_password: qwerty  children:
    windows_west:  # this is a group
      hosts:       # hosts        server2022:  # this is a host      vars:        # inventory group_vars/*
        ansible_user: student
        ansible_password: GoAlta3!   # this has higher precedence than inventory group_vars/all (this value wins)
        ansible_connection: winrm
        ansible_winrm_transport: basic        ansible_port: 5985 # http, 5986 https 
